name: Build LaTeX document

on:
  push:
  workflow_dispatch:
    

jobs:
  build:
    name: build LaTex
    runs-on: ubuntu-18.04
    env:
      SRC_DIR: ./literature
      SRC_FILE: thesis.tex
      TARGET_DIR: build
      TARGET_FILE: thesis.pdf

    # steps:
    
    #   - name: Set up Git repository
    #     uses: actions/checkout@v2
    #   - name: Compile LaTeX document
    #     uses: dante-ev/latex-action@latest
    #     with:
    #       root_file: ${{ env.LATEX_DIR }}/${{ env.LATEX_FILE }}    
      
    steps:
    
    - name: Clone Repo
      uses: actions/checkout@v3
    
    - name: Prepare for build
      run: |
        sudo apt install biber
    
    - name: Build LaTeX Document
      uses: lyuwen/build-latex-action@v1.0.1
      id: textbuild
      with:
        directory: ./literature
        file: thesis.tex
        # directory: $ {{ env.SRC_DIR }}
        # file: ${{ env.SRC_FILE }}

        options: -shell-escape -f --synctex=1 
    - name: Prepare for publish
      run: |
        mkdir build
        cp ${{ steps.texbuild.outputs.output }} ./build/thesis.pdf
        cd ./build && bash ../prepare_for_publish.sh,
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.texbuild.outputs.output }}
        path: ${{ steps.texbuild.outputs.output }}
