name: build

on: [workflow_dispatch,push]

jobs:
  name: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Build LaTeX Document
        # You may pin to the exact commit or the version.
        # uses: lyuwen/build-latex-action@2b0d798c169334fd2fe161fcaf48fcd24dc38c6c
        uses: lyuwen/build-latex-action@v1.0.1
        with:
          # Name of the file to build.
          file: # default is main.tex
          # The directory to build from.
          directory: # optional, default is .
          # list of other options.
          options: # optional, default is 
